strawberry_django/resolvers.py, tests/test_mutation.py, tests/test_permissions.py
can do
```graphql
mutation {
createItems(data: [{name: "item1"}, {name: "item2"}]) {
id
}
}
```
Keep the `createItem` at the same time.
=> Batch create mutation

README.md, poetry.lock, pyproject.toml, strawberry_django/__init__.py, strawberry_django/filters.py, tests/filters/test_filter_fields.py, tests/filters/test_filter_import.py, tests/filters/test_filter_query.py
Some things to consider:
- Should we make "django-filters" an optional dependency?
- How do we implement this into the library? I suppose it should be optional, and easy to modify.
We could add global settings eg:
```
STRAWBERRY_DJANGO_GENERATE_FILTERS = "default to false, when set true we raise error when its not installed"
STRAWBERRY_DJANGO_FILTER_FACTORY = "defaults_to_django-filters_factory_fn"
```
And also allow for overwriting it in specific queries.
=> Implement django-filters for filter generation

strawberry_django/filters.py
Test schema becomes:
```
type BerryFruit {
id: ID!
name: String!
nameUpper: String!
nameLower: String!
}
type Group {
id: ID!
name: String!
users: [User!]
}
type Query {
user(pk: ID): User!
users: [User!]!
group(pk: ID): Group!
groups: [Group!]!
berries: [BerryFruit!]!
}
type User {
id: ID!
name: String!
group: Group
}
```
=> Removes pk argument on model relations

pyproject.toml
Strawberry 0.69 has quite a few changes that are not compatible with
strawberry-django, we'll send another PR to fix them, but for now we 
should pin the version
=> Use Strawberry earlier than 0.69

strawberry_django/mutations/mutations.py, tests/mutations/test_permission_classes.py
Django mutations couldn't handle permissions, but adding the keyword argument `permission_classes` to each django mutation allow the permissions to work as it already inherits the functionality from the StrawberryField class, it just needed to be wired
=> Add permissions to django mutations

strawberry_django/auth/mutations.py, tests/auth/test_mutations.py
This fixes the security flaw of #45 where `auth.register` saves unhashed passwords.
=> Fix a bug related to creating users with unhashed passwords

strawberry_django/fields/types.py, strawberry_django/utils.py, tests/fields/test_types.py, tests/test_types.py, tests/types.py
Previously, when `from __future__ import annotations` was added to a file defining fields with the `auto` annotation, resolving failed because of `TypeError: {Type} fields cannot be resolved. Unexpected type '<class 'strawberry_django.fields.types.auto'>'`.
This PR updates the `is_auto` function to detect such annotations.
Fixes #52.
=> Fix detecting `auto` annotations when postponed evaluation is used

strawberry_django/ordering.py
In this example, the `supplier__name` order arg was generated first, and the subsequent `name` arg was also prefixed with `supplier__`.
```graphql
query {
inventoryItems(order: {
supplier: {
name: ASC
},
name: ASC
}) {
name
supplier {
name
}
}
}
=> Fixed issue with generating order args

.gitignore
Change the gitignore to match the one in the github/gitignore repository (https://github.com/github/gitignore/blob/main/Python.gitignore). This new gitignore is inclusive off all off the different python development environments and will make it easier for people with different setups to contribute without worrying about checking in unneeded files
=> Update .gitignore to the python standard

strawberry_django/filters.py, tests/filters/test_filters.py
Often in Django you will add `ChoiceField` to a model. With Django >= 3.0, you can now build enums that work for choices (https://docs.djangoproject.com/en/3.2/ref/models/fields/#enumeration-types). Using this, we can use the same Choices to build Strawberry Enums to use for filters.
For example, you can now:
```python
class ColorChoices(TextChoices):
blue = "BLUE"
red = "RED"
class Bags(models.Model):
color = models.ChoiceField(TextChoices)
@strawberry.enum
class ColorEnum(ColorChoices):
...
@strawberry_django.filters.filter(Bags)
class BagFilter:
color: ColorEnum
```
This will allow the GraphQL to expose the Enum options and enable filtering using that Enum.
Prior to this, a user would have to define the enum filter method explicitly using:
```python …
```
=> feat: add Enum support to filtering

strawberry_django/fields/field.py
The current MRO applies the ordering before any filters are applied. This is an issue if your filter uses any annotations to do its filtering, as `Queryset`s lose all of their ordering when an annotation is applied. To solve for this, we can change the MRO of `get_queryset` on `StrawberryDjangoField` to apply the filters first, and the ordering after, there by removing the issue
=> Fix ordering with custom filters

strawberry_django/filters.py, tests/filters/test_filters.py
The current behavior is that every filters argument is treated as filter. But filters can also be an arbitrary argument which should not trigger the filter logic.
This MR prevents this by applying checks if filters is really a filter
=> bugfix: ignore filters argument if it is an arbitary argument

docs/guides/quick-start.md
Example fails without setting fruits in query to strawberry.django.field()
Added `= strawberry.django.field()` into the first query example. This is written correctly on the main README.md so this example is now consistent. 
*
- [] I have read the CONTRIBUTING document.
=> Fixing Quick Start

strawberry_django/mutations/mutations.py
You may now use the "description" kwarg in any of the CUD mutations to utilize Strawberry's annotations.
Example:
```py
@strawberry.type
class Mutation:
createTag: Tag = mutations.create(TagInput, description="Create a tag with title and description.")
```
Note:  Using **kwargs here may have unintended consequences, but all the tests passed.
=> Fix #110 - Add **kwargs passthrough on CUD mutations, enables "description" annotation from Strawberry.

strawberry_django/fields/field.py, strawberry_django/filters.py, strawberry_django/ordering.py, strawberry_django/pagination.py
The current MRO of `StrawberryDjangoField` has it applying pagination before the `StrawberryDjangoFieldBase.get_queryset` resolves. Since pagination does array slicing, if you have a custom `get_queryset` defined on the type, it will raise the following error:
```
AssertionError: Cannot filter a query once a slice has been taken.
```
By changing the MRO to have pagination come after field base, we will avoid this issue, since pagination will be applied last
=> Change order of inheritance for `StrawberryDjangoField`

strawberry_django/filters.py
Update `build_filter_kwargs` to handle when an `Enum` is provided to the `FilterLookup`. This is similar to #100, but adds support for if the `Enum` is nested
=> feat: allow Enums to work with FilterLookup

.gitignore, strawberry_django/fields/field.py, tests/fields/test_attributes.py
When attempting to add field-level permissions to a model, e.g. 
```python
@strawberry_django.type(FieldAttributeModel)
class Type:
field: auto = strawberry.field(permission_classes=[TestPermission])
```
I expected that the `TestPermission` class would be applied to that field when resolving. It appeared that the permissions classes had been stripped from the field definition though.
This PR updates `StrawberryDjangoField.from_field()` to pass through all of the attributes which may be needed.
I'd be happy to add some further tests if required?
=> fix: pass through more field attributes

strawberry_django/fields/types.py, tests/auth/test_types.py, tests/fields/test_relations.py, tests/fields/test_types.py, tests/types2/test_type.py
This PR is intended to fix #128. Reverse-related fields like `ManyToManyRel` and `ManyToOneRel` are now resolved as non-null lists, instead of nullable lists, since a query of such relations from the database will always be a list. 
* #128
=> fix: resolve `ManyToManyRel` and `ManyToOneRel` as non-null lists

strawberry_django/fields/types.py, tests/fields/test_types.py
Ensures that any Django model field that is not recognized by strawberry_django will cause `NotImplementedError` to be raised with a helpful message
This improves the behavior for models using [GeoDjango Spatial Fields](https://docs.djangoproject.com/en/3.2/ref/contrib/gis/model-api/#spatial-field-types), which previously would raise a cryptic `KeyError`.
Added tests:
- `tests/fields/test_types.py::test_notimplemented`
=> fix: Raise NotImplementedError on unknown Django fields

README.md, docs/index.md, docs/references/fields.md, docs/references/settings.md, docs/references/types.md, mkdocs.yml, strawberry_django/settings.py, strawberry_django/type.py, tests/models.py, tests/test_settings.py, tests/test_types.py
Automatically add Django model docstring and field `help_text` to the Strawberry type description and field descriptions, respectively.
These descriptions can be overridden by passing the `description` kwarg to `strawberry.django.type()` or `strawberry.django.field()`.
Added tests:
- `tests/test_types.py::test_field_metadata_preserved`
- `tests/test_types.py::test_field_metadata_overridden`
=> feat: Use Django textual metadata in GraphQL 

docs/references/ordering.md, strawberry_django/ordering.py, tests/test_ordering.py
The `@strawberry.django.type` annotion accepts `filters` and `order` parameters, but only `filters` is properly used as a default for fields. This PR fixes the inheritance of the `order` parameter. The code for ordering is based of the existing code for filtering. Additionally, this PR documents this feature similar to the filters documentation.
* https://github.com/strawberry-graphql/strawberry-graphql-django/issues/96
=> Fix field ordering inheritance

poetry.lock, pyproject.toml
The [v0.132.1](https://github.com/strawberry-graphql/strawberry/releases/tag/0.132.1) release of Strawberry broke mutations and filtering in Strawberry Django. I have created a separate PR to fix it but it's probably worth releasing a version first which pins Strawberry to <0.132.1 in case there are other reasons people can't upgrade.
*
=> Pin strawberry-graphql to <0.132.1

strawberry_django/utils.py
When:
1. Using a custom field class in a type
2. It's processed by `type.get_field` is called on an instance of a custom field
3. The custom field class's `from_field` wants to replicate similar functionality to `StrawberryDjangoField.from_field`
It will be useful to have the `is_strawberry_django_field` use the `StrawberryDjangoFieldBase` class as it's means of detecting a strawberry-django field class since that will also be used in a custom class.
I don't believe this change will affect any existing usecase
=> Broaden is_strawberry_django_field to support custom field classes

strawberry_django/settings.py
`from typing import TypedDict` breaks support for Python 3.7, see https://github.com/python/typing_extensions#included-items.
=> import TypedDict from typing_extensions for Python 3.7

strawberry_django/fields/field.py, strawberry_django/filters.py, strawberry_django/ordering.py, strawberry_django/pagination.py
Changed base classes for `StrawberryDjangoField` to allow overloading filter, order and pagination of queryset without too much hassle. If someone were to want to change how filtering works and supply a custom filter type - they'd have to subclass `StrawberryDjangoField` and change the `get_queryset` method which already calls `StrawberryDjangoFieldFilters.get_queryset` which implements the filtering in a unrelated function that cannot be overrwritten - with this change they'd just have to overload `_apply_filters`.
Also added type hints to the methods.
=> Implementing filter, order and pagination in `StrawberryDjangoField` super classes

strawberry_django/filters.py, tests/filters/test_filters.py
This patch allows passing the info object to filters, catering for use cases like filtering with respect to the logged in user (which, its relative cookie will be passed via the input object).
At the same time, it addresses existing codebase and not breaking them by performing analysis on the filter function provided. If the `info` parameter exists, then it is passed. Else not.
* Fixes as per discussion here: https://discord.com/channels/689806334337482765/1025667620407619614 
* Personally decided against rewriting a 'resolvers' support code as not only I think it will potentially break more codebase, it will also increase complexity
=> Allow passing info in filters

strawberry_django/filters.py, tests/filters/test_filters.py
Continuing:
- https://github.com/strawberry-graphql/strawberry-graphql-django/pull/191
This patch allows passing info into overridden 'filter' function.
N/A
=> Pass info for generic filter type

docs/references/types.md
This PR updates the relevent documentation for the removal of the `self` argument in `get_queryset` for [Release 0.5.4](https://github.com/strawberry-graphql/strawberry-graphql-django/releases/tag/v0.5.4)
N/A
=> Updates documentation for `get_queryset`

strawberry_django/filters.py, tests/test_queries.py
It's just a one line correction to make pk argument required when querying a single django object
edit: and test fot required pk argument
=> make pk argument required when querying single object

strawberry_django/filters.py, tests/filters/test_filters.py, tests/models.py
Instead of checking if the field is a relation or not, just check if
it is defined in a root type (e.g. a `Query`). If it is not, do not
insert the pk argument for it.
This fixes a lot of issues like:
1) Defining a field with a name different from the relation
2) Defining a field for a function or property inside the model
3) etc
Fix #215
Fix #235
Fix #245
=> refactor: do not insert `pk` arguments inside non root fields

poetry.lock, pyproject.toml, strawberry_django/fields/types.py, strawberry_django/settings.py, tests/test_enums.py, tests/test_settings.py
feat: enum integration
This enables exposing fields with choices in 2 ways, ported from strawberry-django-plus:
1. It integrates with [django-choices-field](https://github.com/bellini666/django-choices-field)
to be able to handle the enum itself that already exists
2. It can optionally auto generate an enum from a field's `choices`
attribute.
Fix #65
Fix #66
=> feat: enum integration

strawberry_django/permissions.py
`strawberry.django.__init__` will try to import everything from this
lib, meaning that if we try to import anything from inside it before
it finished loading us will produce a circular import issue.
=> fix: do not import anything from `strawberry.django` that is not in this lib

poetry.lock, pyproject.toml, strawberry_django/type.py
strawberry 0.192.2 caused a regression on type resolving for
types inheriting other types.
Resetting the cache for an existing annotation when creating a new
type fixes the issue.
Related: https://github.com/strawberry-graphql/strawberry/pull/2918#issuecomment-1622091675
=> fix: reset annotation cache to fix some inheritance issues

poetry.lock, pyproject.toml, strawberry_django/fields/base.py, strawberry_django/optimizer.py, tests/projects/schema.py, tests/projects/snapshots/schema.gql, tests/test_optimizer.py
This PR removes the usage of `concrete_of`, which was causing issues when 
using specialized types, like this:
```python
import strawberry
from strawberry import Schema
from strawberry.extensions import FieldExtension
from strawberry.field import StrawberryField
from typing import Generic, TypeVar
T = TypeVar("T")
class CheckAtRuntime(FieldExtension):
def apply(self, field: StrawberryField) -> None:
print('concrete_of when applying extension is', field.type.__strawberry_definition__.concrete_of)
def resolve(self, next_, source, info, **kwargs):
return next_(source, info, **kwargs)
@strawberry.type
class MyGenericType(Generic[T]):
my_value: T
@strawberry.type
class MyConcreteType(MyGenericType[int]):
pass
@strawberry.type
class Query:
@strawberry.field(extensions=[CheckAtRuntime()])
def …
```
=> Remove usage of `concrete_of`

strawberry_django/fields/types.py, tests/test_enums.py
It seems that `GENERATE_ENUMS_FROM_CHOICES` breaks `strawberry.auto` types with this error:
```
TypeError: DjangoModelStrawberryType fields cannot be resolved. 'NoneType' object is not iterable
```
*
=> Handle Django GENERATE_ENUMS_FROM_CHOICES with strawberry.auto

docs/guide/types.md, strawberry_django/fields/field.py, tests/projects/schema.py, tests/test_queries.py
=> fix: pass **kwargs to the type's `get_queryset` when defined

strawberry_django/fields/types.py
If TYPE_DESCRIPTION_FROM_MODEL_DOCSTRING is set to True this will lead to crashes in many instances when there's no Python docstring provided.
This looks like a typo.
=> Fix missing model docstring crash

docs/guide/filters.md, docs/guide/relay.md, docs/guide/settings.md, strawberry_django/fields/types.py, strawberry_django/settings.py, tests/fields/test_attributes.py, tests/test_settings.py
`strawberry-django-plus` used to do that, but when migrating this
I thought it would be enough to check if the type itself inherits from
`relay.Node`.
It turns out that it is not, specially for filters as those doesn't
inherit from `relay.Node`.
This adds an option to allow the user to use `ID` or `GlobalID`
for their auto fields, meaning that someone that only uses `Node`
types can set `MAP_AUTO_ID_AS_GLOBAL_ID=True` to make sure that
it will only use `GlobalID` to map those.
=> refactor!: use a setting to decide if we should map fields to relay types or not

docs/guide/fields.md, strawberry_django/type.py, tests/models.py, tests/test_types.py
Per [the discussion around issue 106](https://github.com/strawberry-graphql/strawberry-graphql-django/issues/106), this PR adds two keyword arguments to the `type` decorator -- `fields` and `exclude`. When provided, these arguments help auto-populate the Strawberry fields from the Django model, giving `strawberry.django` similar behavior to the `strawberry.pydantic` and `graphene-django` libraries.
Note that the core of the work was pulled from [the prior repository for `strawberry-django-plus`](https://github.com/blb-ventures/strawberry-django-plus/issues/85), and real credit goes to @mhdismail.
When included, `fields` can be:
* `__all__`. Automatically include all Django model fields, using `strawberry.auto` as the type annotation.
* `[<List of field names>]`. Include the listed Django …
=> Add new keywords "fields" and "exclude" to type decorator for auto-population of Django model fields

strawberry_django/fields/types.py, tests/test_enums.py
- Resolved a bug that occurred when using IntegerChoices instead of django_choices_field.
- The error message was as follows: TypeError: ChoicesType fields cannot be resolved. Cannot unpack non-iterable int object.
- Added unit tests for the conversion of TextChoices and IntegerChoices to Enums without using django_choices_field.
- These tests aim to confirm consistency in behavior:
- When handling TextChoices and IntegerChoices without using django_choices_field.
- When handling choices that are simply specified as tuples.
*
=> Fix TypeError with IntegerChoices and Add Tests for Enum Conversion without django_choices_field

poetry.lock, pyproject.toml, strawberry_django/fields/base.py, strawberry_django/optimizer.py, strawberry_django/utils/inspect.py
strawberry 0.199.0 changed the way generic type vars are handled to support the new generic syntax in Python 3.12.
This release adjusts our usage of generic type vars to match the new behaviour.
Fix #325
=> feat: support strawberry 0.199.0+

docs/guide/optimizer.md
The correct annotation should be `@strawberry.django.type` and not `@strawberry.django`. Otherwise you will get a "module is not callable" error.
N/A
=> Fix typo in optimizer docs for `strawberry.django.type` annotation

strawberry_django/mutations/fields.py
=> refactor: strawberry.union is deprecated, use `Annotated` instead

docs/guide/mutations.md, strawberry_django/fields/types.py, strawberry_django/mutations/fields.py, tests/projects/schema.py, tests/projects/snapshots/schema.gql, tests/test_input_mutations.py
Extends the `OperationMessage` by a `code` attribute that is set to the `ValidationError.code` if available.
I changed the test project to apply Djangos default validation in order to test that error codes used by Django internally are passed through as expected.  This had the side-effect of turning a `datetime` object into a `date` object in an otherwise unrelated test.
* #356
=> feat: Add ValidationError code to OperationMessage

strawberry_django/mutations/resolvers.py
Resolves the issue described in #360: Support updating related objects with `unique_together` on the foreign key where the data identifies a single object in the database.
* #360
=> fix: Update related objects with unique_together

strawberry_django/filters.py, tests/filters/test_filters.py
Enum used in filters are evaluated to their `.value` for doing Django queries.
Unfortunately if a FilterLookup is used and a list is used for a lookup, then this transformation is not done, resulting in non-working django filter.
The correction is to check is the value is a non-empty list for at least one Enum and then create a new list with the `.value` of each enum.
I have added some unit tests.
*
=> Support inList and nInList lookup in filters on enum

docs/guide/relay.md
Updating the code snippet to a working example and clarify some of the name choices
The code sample seems to be from a different library, or older version.  This made setting up relay very cryptic and rather confusing.  Sample has been adjusted to reflect a working example.
Broken docs
=> Update relay.md to working example

strawberry_django/type.py
strawberry_django.interface decorator
cf. https://github.com/strawberry-graphql/strawberry-graphql-django/issues/369
=> Expose disable_optimization argument on

strawberry_django/optimizer.py, tests/test_optimizer.py, tests/utils.py
This PR aims to resolve issue #379 .
I included a reproducible test and a suggested fix, where the `Prefetch` object gets deepcopied to avoid the side effects from `add_prefix`. 
Considerations:
- There were multiple ways to do this, including copying the OptimizerStore at a higher level in the execution stack, but this should be the least invasive one 
- I used deepcopy now as Prefetch didn't offer an easier way of copying the object that I know of, I'm happy about suggestions on improving this
I'm also very open for improving the test case included. If you know a better way on how to do it without the custom type setup, please let me know.
* #379 
I love the work you do here, thanks a lot for the really awesome work! ❤️
=> Fix: DjangoOptimizerExtension corrupts nested objects' fields' prefetch objects

docs/faq.md, strawberry_django/auth/mutations.py, strawberry_django/auth/utils.py, strawberry_django/utils/requests.py
The context object can turn into a dict when using ASGI.  This pull requests accounts for both ASGI and WSGI conditions and replaces the use of `info.context.request` with `get_request(info)`
=> compatibility ASGI/websockets get_request, login and logout

docs/guide/optimizer.md
Happened to notice what seemed to be typos in the docs around the optimizer plugin, so fixed them here.
I haven't yet used strawberry, but thanks for building this great django extension and documenting it well!
n/a
=> docs: Fix typos in optimization examples

docs/guide/permissions.md, strawberry_django/permissions.py
There seemed to be some stale references to class names that don't exist (e.g., `HasObjPerm`, `ObjPermRequired`), so this changes them to refer to the current permission directive class names.
I believe I made these updates correctly, but haven't actually used the library yet myself, so please let me know if anything needs tweaking.
n/a
=> docs: Fix typos in object-level Permissions documentation

strawberry_django/fields/field.py, strawberry_django/type.py, tests/test_type.py
When a type is using a custom field, inheriting from it should not change that field back to a `StrawberryDjangoField`
Fix #414
=> fix: make sure custom fields are kept during inheritance

strawberry_django/filters.py
Fix for #432
really and only push AND, OR and NOT to the end.
* Fix https://github.com/strawberry-graphql/strawberry-graphql-django/issues/432
=> fix: fix #424, really push OR, AND and NOT to the end

strawberry_django/permissions.py, tests/projects/schema.py, tests/projects/snapshots/schema.gql, tests/test_permissions.py
The HasPerm extension  called in an async context get_current_user. This caused decorated async fields to crash
The test schema was updated for an example.
This PR fixes also a minor bug in another test: the query execution was missing
=> fix: HasPerm on async fields, fix missing query in another test

docs/guide/resolvers.md
Fix resolvers.md doc.
`strawberry.django` does not exist. It should be `strawberry_django`.
*
=> fix(docs): resolvers.md strawberry_django import

docs/guide/fields.md
The `field_type_map` example docs is broken because the import path is wrong. This fixes the import, and also adds a models import so this code actually works.
=> Fix code example on updating `field_type_map`.

strawberry_django/fields/base.py, tests/relay/test_fields.py
Fields using extensions that only support async resolution needs to be marked as `is_async = True`.
Fix #433
=> fix: support for fields using async only extensions

strawberry_django/auth/mutations.py, strawberry_django/mutations/fields.py, strawberry_django/mutations/resolvers.py, tests/mutations/conftest.py, tests/mutations/test_mutations.py, tests/projects/schema.py
This PR allows updates of nested fields, i.e.
- update the field by setting the ID
- add copies of Child by leaving the ID unset
- remove a Child by omitting it
The `update_m2m`, `parse_data` and the `_parse_pk` methods were changed.  `_parse_pk` does now return the id as well. If `parse_data` finds an UNSET id, the id is still returned. The id is used to check if a new object is to be created or not. If we have an Input type, the ID is not part of the `data`-dict. This means, we perform a `get_or_create`.
Since `key_attr` can be used to change the primary key from `id` to an "arbitrary" value, major API changes had to be made. This was proposed in https://github.com/strawberry-graphql/strawberry-graphql-django/issues/383.
I am not sure, if this leads to breaking changes - a couple of …
=> Allow updates of nested fields

strawberry_django/optimizer.py, tests/projects/schema.py, tests/projects/snapshots/schema.gql, tests/test_optimizer.py
When doing `select_related=["foo"]` and not doing `only=["foo_<something>"]`, we should add
`"foo"` to the only field to make sure none of its fields will be deferred.
Fix #455
=> feat(optimizer): Do not defer select_related fields if no only was specified

strawberry_django/fields/field.py, strawberry_django/resolvers.py, tests/test_queries.py
=> fix: Return `null` on empty files/images

strawberry_django/optimizer.py
Only 1 subtype of an interface types (e.g Node) is optimized. This PR fixes the optimizer's ```_interfaces`` cache, so that all interfaces are considered for optimization. I assume that the cache was introduced to avoid a performance hit (having to iterate over all the schema's types) every time an interface has to be optimized.
Before this PR, the following would happen. Suppose that we have A and B, both implementing the Node interface:
- We resolve node for an instance of A: The ``_interfaces`` cache is empty. The optimizer will add to the ``_interfaces`` cache only A, which will get all the optimization hints
- We resolve a node for an instance of B: The ``_interfaces`` cache contains only A. The optimizer will fail to optimize B.
=> fix: cache definitions in optimizer

strawberry_django/fields/field.py, tests/projects/schema.py, tests/projects/snapshots/schema.gql, tests/test_permissions.py
Fixes an error when trying to apply permission checks using the `HasRetvalPerm` extension on a paginated list. 
> TypeError: Cannot filter a query once a slice has been taken.
Fix https://github.com/strawberry-graphql/strawberry-django/issues/471
=> Fix permissioned pagination

strawberry_django/fields/field.py, strawberry_django/resolvers.py, tests/fields/test_get_result.py
Currently we have to `qs._fetch_all()` because graphql-core will try to iterate
over the `QuerySet` in a sync way, thus causing issues when running ASGI.
This adds a way for extensions to prevent that from happening, as discussed in https://github.com/strawberry-graphql/strawberry/issues/3364
When `grapghql-core` 3.3.0 is released we can probably stop fetching results at all,
as it will give preference to use `__aiter__` if the object provides one (and the `QuerySet` does)
=> feat: allow extensions to prevent results from being fetched

strawberry_django/mutations/resolvers.py, tests/mutations/test_relationship.py
Fix for [issue described in #487](**[url](https://github.com/strawberry-graphql/strawberry-django/issues/487)**)
Notes:
- Used django_assert_max_num_queries to write test
- Reduced the number of queries for a "patch" update from 25 to 12
- `test_relation.py` was blank so deleted it.
- As a new contributor, I found it confusing which tests go where so added docstring to `test_relationship` to clarify my understanding
* https://github.com/strawberry-graphql/strawberry-django/issues/487
=> fix: OneToManyInput saves and runs validation on foreign key #487

strawberry_django/fields/types.py, tests/test_enums.py
The generate enum from choices feature fail when choice description is a django's lazy string (gettext_lazy used with translation framework) 
Use `str()` on description to trigger string translation when generating Enum.
Fix #489
=> fix: use str() to trigger eventual django's gettext_lazy string

strawberry_django/mutations/resolvers.py, tests/test_enums.py, tests/test_input_mutations.py
If `GENERATE_ENUMS_FROM_CHOICES` is set to `True`, mutations with enum input values will resolve the input type as an enum. When the input is parsed, it tries to save the field as an enum instead of a string value, causing Django to throw a ValidationError `"Value 'ExampleEnum.VALUE' is not a valid choice."`. This PR addresses this issue by parsing the enum and returning the enum value.
Fix https://github.com/strawberry-graphql/strawberry-django/issues/491
=> fix: Add support for generated enums in mutation input

strawberry_django/fields/filter_order.py, tests/filters/test_filters.py, tests/filters/test_filters_v2.py
This PR fixes a problem with the new filter API in async environments
It is likely a typo
=> fix: async with new filter API (assert queryset is wrong)

docs/guide/filters.md, strawberry_django/fields/filter_order.py, strawberry_django/fields/filter_types.py, strawberry_django/filters.py, tests/filters/test_filters_v2.py
Adds option not to resolve value of custom filter method via `@strawberry_django.filter_field(resolve_value=False)`.
* https://github.com/strawberry-graphql/strawberry-django/issues/509
=> feat: filter_field optional value resolution

docs/guide/filters.md
This fixes some small typos:
FilterLookups -> FilterLookup
proces_filters -> process_filters
=> Fix typos in filtering documentation

strawberry_django/mutations/resolvers.py, tests/mutations/test_filter_mutations.py
When running a batched delete mutation, if no objects are in the filter set, the mutation should be no-op, and an empty array should be returned. This matches the behavior of a batched update and also ensures idempotence.
Current behavior: An empty set throws an error
Expected behavior: An empty set does not throw an error
Scope of change: 
- Remove a seemingly necessary assert statement. 
- Add some tests (including a breaking test)
n/a
=> fix: Delete mutation should not throw error if no objects in filterset

strawberry_django/optimizer.py, tests/projects/schema.py, tests/projects/snapshots/schema.gql, tests/projects/snapshots/schema_with_inheritance.gql, tests/test_optimizer.py
The strawberry-django optimizer can automatically add `select_related` and `only` clauses to a queryset. However, it currently fails if you enable the `only` optimization while using querysets that already have `select_related`s on them.
We use strawberry at work, and have a model like:
```
class MyManager(models.Manager):
def get_queryset(self):
return super().get_queryset().select_related("foo")
class MyModel(models.Model):
objects = MyManager()
foo = models.ForeignKey(Foo, on_delete=models.CASCADE)
```
This causes issues with the optimizer if you try to execute a graphQL query that *doesn't* include `foo`: you get errors like `Field cannot be both deferred and traversed using select_related at the same time`. We've actually been running without the `only` optimization for a long time …
=> fix(optimizer): handle existing select_related in querysets

.github/workflows/tests.yml, pyproject.toml, strawberry_django/fields/field.py, strawberry_django/fields/types.py, strawberry_django/optimizer.py, strawberry_django/pagination.py, strawberry_django/queryset.py, strawberry_django/relay.py, strawberry_django/resolvers.py, tests/fields/test_input.py, tests/fields/test_types.py, tests/filters/test_filters.py, tests/filters/test_filters_v2.py, tests/projects/schema.py, tests/projects/snapshots/schema.gql, tests/projects/snapshots/schema_with_inheritance.gql, tests/test_optimizer.py
This is going to enable optimization of nested relations even when using filters/ordering/pagination, which previously would mean throwing the results away and fetching new ones, causing more than n+1 issues.
Note: Although nested connections are being optimized as well, we are only doing that for those annotated with `ListConnection` and `ListConnectionWithTotalCount`, as custom connections may contain more complex code which are not safe to be optimized the way we are doing here.
We are also dropping support for Django versions older than 4.2 as we cannot filter over window functions in older versions. That is also a recommendation from Django itself when 5.0 was released: https://docs.djangoproject.com/en/5.0/releases/5.0
Fix #337
Fix #340
Fix #345
Fix #389
Fix #521
=> feat: Nested optimization for lists and connections

poetry.lock, pyproject.toml, strawberry_django/relay.py, tests/relay/mptt/a.py, tests/relay/mptt/b.py, tests/relay/mptt/models.py, tests/relay/mptt/snapshots/test_lazy_annotations/test_lazy_type_annotations_in_schema/authors_and_books_schema.gql, tests/relay/mptt/test_lazy_annotations.py, tests/relay/mptt/test_nested_children.py
When resolving the connection from cache, we were missing setting `nodes` in it 🤦‍♂️
We do have a test that was passing with this, but MPTT triggered the issue. The issue was probably happening to corner cases as well
Used https://github.com/strawberry-graphql/strawberry-django/pull/551 as a base for the reproduction, but adjusted it to avoid depending on python 3.9
Fix https://github.com/strawberry-graphql/strawberry-django/issues/552
=> fix: fix optimized nested connections failing to access totalCount

strawberry_django/optimizer.py, tests/node_polymorphism/models.py, tests/node_polymorphism/schema.py, tests/node_polymorphism/test_optimizer.py
Add node polymorphism tests and related schema
Update asserts in optimizer.py -> To be double checked before merge
=> Test optimizer with polymorphic relay node

strawberry_django/optimizer.py, tests/projects/schema.py, tests/projects/snapshots/schema.gql, tests/projects/snapshots/schema_with_inheritance.gql, tests/test_pagination.py
Fix https://github.com/strawberry-graphql/strawberry-django/issues/563
=> fix: Fix nested pagination/filtering/ordering not working when "only optimization" is disabled

strawberry_django/middlewares/debug_toolbar.py
`_HTML_TYPES` got moved to somewhere else.
Instead of trying to import from both places, just copy it. It is a small list that should not suffer from changes often, and also prevents us from having to import a private member from the module.
Fix #586
=> fix: Fix debug toolbar upgrade issue
