- README.md
- examples/django/app/schema.py
Add 
```
@strawberry.field
def something(self, info, root) -> List[Resolver.output_type]:
```
as discussed in https://github.com/strawberry-graphql/strawberry-graphql-django/issues/8
And add some useful django auth examples.
> Add examples to readme and example repo

- strawberry_django/utils.py
See https://github.com/django/django/pull/14345.
> updated the way event loop is detected in 'is_async'

- poetry.lock
Upgrade package versions to unblock https://github.com/strawberry-graphql/strawberry-graphql-django/pull/93
> build: update packages

- strawberry_django/filters.py
Closed https://github.com/strawberry-graphql/strawberry-graphql-django/issues/84
> Fix filtering cannot use relational reflection fields

- poetry.lock
- pyproject.toml
- strawberry_django/arguments.py
- strawberry_django/fields/field.py
- strawberry_django/fields/types.py
- strawberry_django/filters.py
- strawberry_django/mutations/fields.py
- strawberry_django/mutations/mutations.py
- strawberry_django/ordering.py
- strawberry_django/pagination.py
- strawberry_django/type.py
- strawberry_django/utils.py
- tests/filters/test_filters.py
> refactor: Change the use of "is_unset" to "is UNSET"

- docs/references/filters.md
Document how to overwrite default filter logic.
> docs: document how to use a custom filter logic

- CHANGELOG.md
- docs/references/mutations.md
- strawberry_django/extensions/django_cache_base.py
- strawberry_django/type.py
> fixed various typos

- strawberry_django/fields/types.py
- tests/fields/test_types.py
This PR is intended to fix #143. I saw in the discord channel that there already exists a `JSON` type so I'm using that one instead of inventing one as did in #143. 
* #143
> feat: link JSONField to strawberry.scalars.JSON

- docs/references/fields.md
Following #135, this PR adds some basic documentation for that field.
In order to really demonstrate it though, it may be helpful if there is a "cookbook" or similar to show some of the usecases. Is that something that should live in the docs too?
> Documentation for overriding the field class

- strawberry_django/extensions/django_cache_base.py
- strawberry_django/fields/field.py
- strawberry_django/fields/types.py
- strawberry_django/type.py
- strawberry_django/utils.py
In the spirit of Strawberry's love of [type hints](https://docs.python.org/3/library/typing.html), I added a bunch of annotations and corrected existing ones after spending time in the code for #160. These changes were made with the intent of improving the feedback given by Pylance while exploring the "types" and "fields" code areas, and to provide implicit documentation of how the functions operate.
The details can be found in the commit messages, which I tried to make as atomic as possible for clarity.
> Add many type hints

- docs/index.md
Adding installation instructions for strawberry-graphql-django
> adding installation with pip

- mkdocs.yml
MkDocs has the default edit_uri pointing to `master` branch and will 404 if different - https://www.mkdocs.org/user-guide/configuration/#edit_uri . This repo has its default branch as `main`. This hopefully fixes the issue of clicking the edit icon
*
> fix(doc): update mkdocs.yml to point to correct branch

- poetry.lock
- pyproject.toml
- strawberry_django/fields/field.py
- strawberry_django/mutations/fields.py
- tests/test_types.py
The [v0.132.1](https://github.com/strawberry-graphql/strawberry/releases/tag/0.132.1) release of strawberry-graphql broke mutations and filtering because it introduced the concept of "basic fields" which skip calling resolvers in certain circumstances. Strawberry-Django doesn't use `base_resolver` for it's custom fields but it does define custom resolvers without implementing the `is_basic_field` property and so the custom resolvers were not longer being called. This PR makes sure that the custom Strawberry Django fields are never treated as "basic" by Strawberry.
It also fixes some tests that were instantiated without keyword arguments. Keyword arguments were required from [v0.128.0](https://github.com/strawberry-graphql/strawberry/releases/tag/0.132.1) of Strawberry.
* fixes …
> Fix mutations and filtering for when using strawberry-graphql >=0.132.1

- strawberry_django/fields/field.py
- tests/test_pagination.py
- tests/test_queries.py
details of the issue can be found at https://github.com/strawberry-graphql/strawberry-graphql-django/issues/187 test cases are also update
Details for the issue can be found at https://github.com/strawberry-graphql/strawberry-graphql-django/issues/187
https://github.com/strawberry-graphql/strawberry-graphql-django/issues/187
> fix: get_queryset sends self in fields.py which it shouldnt

- poetry.lock
- pyproject.toml
- strawberry_django/type.py
- tests/fields/test_attributes.py
This fixes #205 
@bellini666 do you think the changes make sense?
> Change how we set the default annotation

- strawberry_django/type.py
- tests/test_types.py
Fix https://github.com/strawberry-graphql/strawberry-graphql-django/issues/209
> fix: Fix resolver annotation resolution

- mkdocs.yml
Typo fix on table of contents.
* None
> fix(typo): Fix typo in table of contents

- .github/actionlint-matcher.json
- .github/workflows/actionlint.yml
- .github/workflows/main.yml
- .pre-commit-config.yaml
This PR adds checks for GitHub Actions files by linting them and catch errors.
> Add actionlint for GitHub Actions files

- .github/workflows/main.yml
- README.md
Adressing https://github.com/strawberry-graphql/strawberry-graphql-django/pull/219#discussion_r1059567089
cc / @kwongtn
> Fix django version matrix.

- docs/references/queries.md
> Started docs for query

- .github/workflows/main.yml
- poetry.lock
- pyproject.toml
- Add Django 4.0 to test matrix as according to [official docs](https://www.djangoproject.com/download/) it will still be supported up till April 2023
- Add Django 4.2 to test matrix to catch any potential bugs before it reaches stable
- Update `pyproject.toml` classifiers
> Add django 4.0,4.2 to tests & updated minor versions

- strawberry_django/type.py
> Fix private field handling

- .github/workflows/main.yml
Update test django version from 4.2a1 to 4.2b1
*
> Update test django version from 4.2a1 to 4.2b1

- RELEASE.md
- pyproject.toml
- strawberry_django/fields/field.py
- strawberry_django/type.py
- strawberry_django/utils.py
- tests/test_relay.py
Fix the compatibility with strawberry.relay
<del>The part which keeps the schema validation crashing is:</del>
<del>the graphql name of the `_id` field is ignored. Instead ´_id´ is transformed to `Id` even with ``auto_camel_case` off, This causes the interface validation to crash.</del>
<del>Seemingly strawberry-graphql-django just ignores graphql names and need some updates </del>
* #258
> add strawberry.relay tests, fix compatibility with relay, fix other issues

- poetry.lock
- pyproject.toml
- strawberry_django/__init__.py
- strawberry_django/fields/base.py
- strawberry_django/fields/field.py
- strawberry_django/fields/types.py
- strawberry_django/filters.py
- strawberry_django/mutations/fields.py
- strawberry_django/ordering.py
- strawberry_django/pagination.py
- strawberry_django/relay.py
- strawberry_django/type.py
- strawberry_django/utils.py
- tests/relay/schema.gql
- tests/relay/schema.py
- tests/relay/test_fields.py
- tests/relay/test_schema.py
- tests/relay/test_types.py
Relay integration ported from strawberry-django-plus, using the official strawberry relay integration
> feat: relay integration

- strawberry_django/descriptors.py
- strawberry_django/fields/field.py
- strawberry_django/type.py
- tests/models.py
- tests/test_descriptors.py
ModelProperty descriptor ported from strawberry-django-plus.
obs. This will be mostly useful for the upcoming "Optimizer" support, where it will be able to pass optimization hints to the `@model_property`
> feat: ModelProperty descriptor

- docs/guide/mutations.md
> Typo fix in documentation

- strawberry_django/fields/types.py
Fixed a typo __dic__, where __dict__ is the intended attribute.
*
> Fixed typo __dic__

- docs/guide/settings.md
Fixed broken link in docs
https://strawberry-graphql.github.io/strawberry-graphql-django/guide/settings/#:~:text=IntegerChoices%20with%20the-,django%2Dchoices%2Dfield,-integration.
In MkDocs, the current directory is treated as `/guide/settings/` in this md file, so `../../` points to the root directory.
*
> docs: update absolute path to relative in markdown file

- strawberry_django/management/commands/export_schema.py
- tests/schema.py
- tests/test_commands.py
This release adds a django command to export strawberry schemas:
```python
manage.py export_schema [SCHEMA_PATH]
```
If you prefer to change the output path of the generated schema. Use the `--path` parameter:
```python
manage.py export_schema [SCHEMA_PATH] --path [OUTPUT_PATH]
```
Fix #280
Fix #164
> feat: add command export schema

- docs/guide/optimizer.md
- [ x] Documentation
*
Not the most important pr ever, but since I ran into this typo, I thought I might as well fix it.
> docs: change one occurence of select_related to prefetch_related

- strawberry_django/utils/typing.py
- tests/test_type.py
Related: https://github.com/strawberry-graphql/strawberry-graphql-django/issues/301#issuecomment-1635390325
> fix: fix an issue where non dataclass annotations where being injected as fields on input types

- strawberry_django/fields/field.py
- strawberry_django/resolvers.py
- tests/fields/test_relations.py
> fix: fix resolving optional fields based on reverse one-to-one relations

- docs/guide/views.md
- Made minor corrections to the sample code in the [Serving the API](https://strawberry-graphql.github.io/strawberry-graphql-django/guide/views/#serving-as-asgi-async) page:
- Corrected the file name.
- Fixed a syntax error.
*
> docs: fix sample code on 'Serving the API'

- docs/guide/filters.md
- strawberry_django/filters.py
- strawberry_django/type.py
- tests/fields/test_attributes.py
- tests/filters/test_filters.py
- tests/filters/test_types.py
- tests/projects/snapshots/schema.gql
- tests/relay/snapshots/schema.gql
> feat: deprecate nSomething in favor of using NOT

- strawberry_django/middlewares/debug_toolbar.py
Fixes issue associated with SHOW_TOOLBAR_CALLBACK settings. This is a duplicate of: https://github.com/strawberry-graphql/strawberry-graphql-django/pull/367
This fixes the type errors associated with that PR.
* https://github.com/strawberry-graphql/strawberry-graphql-django/issues/366
- [] I have added tests to cover my changes.
> FIX: DEBUG_TOOLBAR_CONFIG consideration

- docs/community-projects.md
Added [strawberry-django-extras](https://github.com/m4riok/strawberry-django-extras) to community-projects.md
*
> docs: Added strawberry-django-extras to community-projects.md

- strawberry_django/fields/field.py
- strawberry_django/filters.py
- strawberry_django/ordering.py
- tests/test_ordering.py
Make sure that the sequence the ordering was given by the client is respected.
Fix #150
> fix: keep ordering sequence

- strawberry_django/mutations/resolvers.py
- tests/models.py
- tests/mutations/test_mutations.py
- tests/types.py
If nested one to many / many to many relations are updated, a `full_clean` is performed on the object to be updated. This ensures that Validators are actually executed.
#398
> feat: Enforce validation for updating nested relations

- strawberry_django/fields/field.py
- strawberry_django/utils/typing.py
This should fix an issue I was having with latest pyright 😊
Not sure if Prefetch in django is actually generic (I'm using django types), that's why I put it behind quotes 😊
> Fix typing issues

- docs/guide/optimizer.md
Fix small errata in Query Optimizer docs page
-
> fix small errata

- docs/guide/resolvers.md
Update a snippet in the resolvers section of the docs which was missing an import and parameter which was a bit confusing as a new user.
*
> fix(docs): Add missing import to resolver snippet

- .gitignore
- poetry.lock
- pyproject.toml
- strawberry_django/mutations/resolvers.py
- tests/conftest.py
- tests/models.py
- tests/mutations/test_mutations.py
- tests/test_types.py
- tests/types.py
> fix: fix files not being saved on create mutation

- strawberry_django/mutations/resolvers.py
- tests/models.py
- tests/mutations/conftest.py
- tests/mutations/test_mutations.py
- tests/types.py
Referring to issue: https://github.com/strawberry-graphql/strawberry-graphql-django/issues/468
This PR will validate the images at dummy-instance level.
Fix https://github.com/strawberry-graphql/strawberry-graphql-django/issues/468
> validate files at dummy-instance level

- strawberry_django/__init__.py
Exposes `apply` and `OffsetPaginationInput` in `strawberry_django/__init__.py` to allow public access.
* https://github.com/strawberry-graphql/strawberry-graphql-django/issues/470
> Expose apply and OffsetPaginationInput publicly

- strawberry_django/optimizer.py
- strawberry_django/permissions.py
- strawberry_django/resolvers.py
- tests/test_optimizer.py
See https://github.com/strawberry-graphql/strawberry-django/issues/532
* Fix #532 
- ~My change requires a change to the documentation.~
- ~I have updated the documentation accordingly.~
> Fix AttributeError when using optimizer and prefetch_related

- strawberry_django/optimizer.py
- strawberry_django/utils/inspect.py
This allows us to simplify our optimizer implementation, and also paves the way for nested optimizations implementation in the near future.
> refactor: Use graphql-core's collect_sub_fields instead of our own implementation

- docs/guide/filters.md
Just fix docs wrong typo on filter docs
*
> fix: wrong typo on filter on fruitfilter

- strawberry_django/mutations/fields.py
> delete unused filters for creating mutations
